name: rxce
description: A application for RxCe course management.
version: 1.0.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  auto_route: ^10.1.2
  bloc: ^9.0.1
  bloc_concurrency: ^0.3.0
  course_package: any
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  stream_transform: ^2.1.1
  talker_bloc_logger: ^5.0.1

dev_dependencies:
  auto_route_generator: ^10.2.4
  bloc_lint: ^0.3.5
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
